services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bd2
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080