
services:
  web:
    build: .
    ports:
      - "8888:8888"
    environment:
      - VIEWS_DIR=/app/internal/views
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bd2
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080